### ISSUE TITLE
Requesting Japanese as Crowdin target language

### ISSUE THREAD

**Issue by pikanji** [lovata/oc-toolbox-plugin#49]
Hi, I like to contribute to the localization of this plugin (also other shopaholic plugins).
Would you add Japanese as Crowdin target language?

**Comment by kharanenka** [comment]
Hi @pikanji! We are not ready to work with Crowdin service yet. We will be slaves if you send us PR in github repository with lang file.
Thanks for you contribution!

**Comment by pikanji** [comment]
Hi @kharanenka! Got it! Thanks!

**Comment by kharanenka** [comment]
Japanese language added. Thanks for your contribution.
